# Generated by Django 5.0.4 on 2025-11-13 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technologie'), ('social', 'Innovation sociale'), ('environment', 'Environnement'), ('health', 'Santé'), ('education', 'Éducation'), ('other', 'Autre')], max_length=50)),
                ('objectives', models.TextField()),
                ('expected_impact', models.TextField()),
                ('resources_needed', models.JSONField(blank=True, default=list)),
                ('current_status', models.CharField(choices=[('idea', 'Idée'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('incubation', 'Incubation'), ('completed', 'Réalisé')], default='idea', max_length=20)),
                ('community_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='draft', max_length=32)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='projects/documents/')),
                ('document_type', models.CharField(choices=[('presentation', 'Présentation'), ('business_plan', 'Business plan'), ('video', 'Vidéo'), ('prototype', 'Prototype'), ('other', 'Autre')], max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document de projet',
                'verbose_name_plural': 'Documents de projet',
            },
        ),
        migrations.CreateModel(
            name='ProjectEngagement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_type', models.CharField(choices=[('view', 'Vue'), ('like', 'Like'), ('share', 'Partage')], max_length=16)),
            ],
            options={
                'verbose_name': 'Engagement projet',
                'verbose_name_plural': 'Engagements projet',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminé')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Étape de projet',
                'verbose_name_plural': 'Étapes de projet',
                'ordering': ('due_date',),
            },
        ),
    ]
