# Generated by Django 5.0.4 on 2025-11-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accompagnement', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='accompagnement.mentorship'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='accompagnement.mentorship'),
        ),
    ]
