# Generated by Django 5.0.4 on 2025-11-13 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('on_hold', 'En pause')], default='queued', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True)),
                ('code_repository', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prototype',
                'verbose_name_plural': 'Prototypes',
            },
        ),
        migrations.CreateModel(
            name='PrototypeTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('column', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'À faire'), ('in_progress', 'En cours'), ('review', 'Revue'), ('done', 'Terminé')], default='backlog', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Tâche prototype',
                'verbose_name_plural': 'Tâches prototype',
                'ordering': ('priority', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('generated_by', models.CharField(default='system', max_length=128)),
            ],
            options={
                'verbose_name': 'Spécification technique',
                'verbose_name_plural': 'Spécifications techniques',
            },
        ),
    ]
