# Generated by Django 5.0.4 on 2025-11-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('prototyping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, related_name='assigned_prototypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prototype',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prototype', to='projects.project'),
        ),
        migrations.AddField(
            model_name='prototypetask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototype_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prototypetask',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prototyping.prototype'),
        ),
        migrations.AddField(
            model_name='technicalspecification',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='prototyping.prototype'),
        ),
    ]
