# Generated by Django 5.0.4 on 2025-11-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientationconversation',
            name='participants',
            field=models.ManyToManyField(related_name='orientation_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orientation.orientationconversation'),
        ),
        migrations.AddField(
            model_name='orientationrequest',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orientation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientationconversation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='orientation.orientationrequest'),
        ),
    ]
