# Generated by Django 5.0.4 on 2025-11-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='sponsors.sponsorprofile'),
        ),
        migrations.AddField(
            model_name='sponsormessage',
            name='sponsorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sponsors.sponsorship'),
        ),
    ]
