# Generated by Django 5.0.4 on 2025-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technologie'), ('social', 'Social'), ('environment', 'Environnement'), ('health', 'Santé'), ('education', 'Éducation')], max_length=50)),
                ('status', models.CharField(choices=[('idea', 'Idée'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('selected', 'Sélectionné')], default='idea', max_length=20)),
                ('objectives', models.TextField(blank=True)),
                ('expected_impact', models.TextField(blank=True)),
                ('required_resources', models.TextField(blank=True)),
                ('community_score', models.FloatField(default=0)),
                ('ai_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
